# Generated by Django 4.0.4 on 2022-05-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='제목')),
                ('email', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
                ('receive_email', models.BooleanField(default=False, verbose_name='이메일 수신')),
                ('category', models.IntegerField(choices=[(1, '주문/배송'), (2, '결제/환불'), (3, '취소/반품/교환'), (4, '멤버십'), (5, '기타')], verbose_name='카테고리')),
                ('phone_number', models.IntegerField(verbose_name='전화번호')),
                ('sms', models.BooleanField(default=False, verbose_name='문자 수신')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField(verbose_name='자주 묻는 질문')),
                ('faq_category', models.IntegerField(choices=[(1, '주문/배송'), (2, '결제/환불'), (3, '취소/반품/교환'), (4, '멤버십'), (5, '기타')], verbose_name='카테고리')),
                ('answer', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
