# Generated by Django 4.0.4 on 2022-05-09 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_answer_editor_faq_editor_alter_answer_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='작성자', to=settings.AUTH_USER_MODEL),
        ),
    ]
