# Generated by Django 4.0.4 on 2022-05-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_inquiry_created_at_inquiry_updated_at_inquiry_writer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='phone_number',
            new_name='phone_num',
        ),
    ]
