# Generated by Django 4.0.4 on 2022-05-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_rename_phone_number_inquiry_phone_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': '자주 묻는 질문'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': '1:1 문의'},
        ),
    ]
