# Generated by Django 4.0.4 on 2022-05-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-created_at',), 'verbose_name_plural': '자주 묻는 질문'},
        ),
    ]
