# Generated by Django 4.0.4 on 2022-05-10 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0009_alter_faq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inquiry_작성자', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
