# Generated by Django 4.0.4 on 2022-05-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0011_alter_answer_editor_alter_answer_writer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-updated_at',), 'verbose_name_plural': '답변'},
        ),
    ]
