# Generated by Django 4.0.4 on 2022-05-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_alter_answer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
    ]
