# Generated by Django 4.0.4 on 2022-05-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0015_alter_inquiry_phone_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ('-created_at',), 'verbose_name': '자주 묻는 질문', 'verbose_name_plural': '자주 묻는 질문'},
        ),
        migrations.AlterModelOptions(
            name='inquiry',
            options={'ordering': ('-updated_at',), 'verbose_name': '1:1 문의', 'verbose_name_plural': '1:1 문의'},
        ),
    ]
