# Generated by Django 4.0.4 on 2022-05-10 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0018_alter_faq_faq_alter_inquiry_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquiry',
            old_name='receive_email',
            new_name='is_email',
        ),
        migrations.RenameField(
            model_name='inquiry',
            old_name='sms',
            new_name='is_phone',
        ),
    ]
