# Generated by Django 4.0.4 on 2022-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0019_rename_receive_email_inquiry_is_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='chellphone',
            field=models.CharField(blank=True, help_text="'-'은 빼고 입력해주세요.", max_length=11, null=True, verbose_name='전화번호'),
        ),
    ]
